from __future__ import annotations

DEFAULT_DEPARTMENT_AGENTS = [
    {
        "key": "hr",
        "name": "HR Agent",
        "department": "human_resources",
        "description": "وكيل الموارد البشرية لسياسات الموظفين والإجازات والتوظيف والتدريب.",
        "keywords": ["موظف", "الموظفين", "موارد بشرية", "hr", "إجازة", "اجازة", "راتب", "توظيف", "تدريب", "دوام", "حضور", "انصراف"],
        "allowed_roles": ["hsaai_admin", "department_manager", "ai_user", "auditor"],
        "knowledge_scopes": ["hr", "human_resources", "policies"],
        "system_prompt": "أنت HR Agent داخل HSAAI. أجب بالعربية الفصحى المختصرة من سياسات الموارد البشرية المعتمدة فقط. لا تفترض معلومات غير موجودة، واطلب توضيحًا عند الغموض.",
        "escalation_target": "HR Service Desk",
        "priority": 20,
    },
    {
        "key": "finance",
        "name": "Finance Agent",
        "department": "finance",
        "description": "وكيل المالية للميزانيات والمصروفات والفواتير والإجراءات المالية.",
        "keywords": ["مالية", "finance", "فاتورة", "فواتير", "مصروف", "مصروفات", "ميزانية", "موازنة", "حساب", "قيود", "اعتماد مالي", "تكلفة"],
        "allowed_roles": ["hsaai_admin", "department_manager", "auditor"],
        "knowledge_scopes": ["finance", "accounting", "policies"],
        "system_prompt": "أنت Finance Agent داخل HSAAI. أجب فقط ضمن السياسات المالية المعتمدة ومصادر RAG المصرح بها. لا تكشف معلومات مالية إلا للمخولين.",
        "escalation_target": "Finance Governance Team",
        "priority": 15,
    },
    {
        "key": "it",
        "name": "IT Support Agent",
        "department": "it",
        "description": "وكيل تقنية المعلومات للدعم الفني والصلاحيات والأنظمة والشبكات.",
        "keywords": ["تقنية", "it", "دعم فني", "الدعم الفني", "كلمة المرور", "صلاحية", "vpn", "شبكة", "نظام", "لا يعمل", "مشكلة", "تذكرة"],
        "allowed_roles": ["hsaai_admin", "department_manager", "ai_user", "auditor"],
        "knowledge_scopes": ["it", "security", "service_desk"],
        "system_prompt": "أنت IT Support Agent داخل HSAAI. ساعد المستخدم بخطوات واضحة، ووجّه الطلب لفريق الدعم عند الحاجة، ولا تطلب كلمات مرور أو أسرار.",
        "escalation_target": "IT Service Desk",
        "priority": 25,
    },
    {
        "key": "procurement",
        "name": "Procurement Agent",
        "department": "procurement",
        "description": "وكيل المشتريات للموردين وطلبات الشراء والمناقصات.",
        "keywords": ["مشتريات", "شراء", "مورد", "موردين", "مناقصة", "عطاء", "توريد", "طلب شراء", "procurement", "vendor", "purchase"],
        "allowed_roles": ["hsaai_admin", "department_manager", "ai_user", "auditor"],
        "knowledge_scopes": ["procurement", "vendors", "contracts"],
        "system_prompt": "أنت Procurement Agent داخل HSAAI. أجب من إجراءات المشتريات المعتمدة، وبيّن خطوات الطلب أو الاعتماد دون تجاوز الصلاحيات.",
        "escalation_target": "Procurement Office",
        "priority": 30,
    },
    {
        "key": "legal",
        "name": "Legal Agent",
        "department": "legal",
        "description": "وكيل الشؤون القانونية للعقود والسياسات والامتثال، ولا يقدم استشارة قانونية نهائية.",
        "keywords": ["قانوني", "الشؤون القانونية", "عقد", "عقود", "امتثال", "لائحة", "مخالفة", "legal", "compliance", "contract"],
        "allowed_roles": ["hsaai_admin", "department_manager", "auditor"],
        "knowledge_scopes": ["legal", "compliance", "contracts"],
        "system_prompt": "أنت Legal Agent داخل HSAAI. قدم معلومات تنظيمية من الوثائق المعتمدة فقط، ولا تقدم رأيًا قانونيًا نهائيًا؛ وجّه المستخدم للمختص القانوني عند الحاجة.",
        "escalation_target": "Legal Department",
        "priority": 10,
    },
    {
        "key": "operations",
        "name": "Operations Agent",
        "department": "operations",
        "description": "وكيل العمليات للإجراءات التشغيلية وسير العمل ومؤشرات الأداء التشغيلية.",
        "keywords": ["عمليات", "تشغيل", "إجراء", "إجراءات", "workflow", "operation", "انتاج", "مخزون", "توريد", "سير العمل"],
        "allowed_roles": ["hsaai_admin", "department_manager", "ai_user", "auditor"],
        "knowledge_scopes": ["operations", "sop", "workflows"],
        "system_prompt": "أنت Operations Agent داخل HSAAI. اشرح الإجراءات التشغيلية المعتمدة بخطوات واضحة ومختصرة، واعتمد على مصادر المؤسسة.",
        "escalation_target": "Operations Management",
        "priority": 35,
    },
    {
        "key": "knowledge",
        "name": "Knowledge Agent",
        "department": "knowledge_management",
        "description": "وكيل إدارة المعرفة للبحث في الوثائق والمصادر والسياسات المعتمدة.",
        "keywords": ["وثيقة", "مستند", "ملف", "مصدر", "قاعدة المعرفة", "بحث", "سياسة", "لائحة", "knowledge", "rag", "document"],
        "allowed_roles": ["hsaai_admin", "knowledge_admin", "document_reviewer", "document_uploader", "department_manager", "ai_user", "auditor"],
        "knowledge_scopes": ["knowledge", "policies", "general"],
        "system_prompt": "أنت Knowledge Agent داخل HSAAI. ابحث في الوثائق المعتمدة فقط، واذكر المصادر عند توفرها، ولا تجب من وثائق غير معتمدة أو غير مصرح بها.",
        "escalation_target": "Knowledge Governance Team",
        "priority": 5,
    },
    {
        "key": "executive",
        "name": "Executive Agent",
        "department": "executive",
        "description": "وكيل الإدارة التنفيذية للتقارير والمؤشرات والملخصات الاستراتيجية.",
        "keywords": ["تنفيذي", "إدارة عليا", "مؤشر", "مؤشرات", "kpi", "تقرير", "تحليل", "استراتيجية", "لوحة", "dashboard", "executive"],
        "allowed_roles": ["hsaai_admin", "department_manager", "auditor"],
        "knowledge_scopes": ["executive", "reports", "analytics"],
        "system_prompt": "أنت Executive Agent داخل HSAAI. قدم ملخصات تنفيذية دقيقة، واربط الإجابات بالمؤشرات والمصادر، ولا تعرض بيانات حساسة إلا للمخولين.",
        "escalation_target": "Executive Office",
        "priority": 1,
    },
]
