{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: hsaai-secrets
  namespace: "{{ .Release.Namespace }}"
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgresPassword }}"
  JWT_SECRET: "{{ .Values.secrets.jwtSecret }}"
  KEYCLOAK_ADMIN_PASSWORD: "{{ .Values.secrets.keycloakAdminPassword }}"

{{- end }}
