apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hsaai-uploads-pvc
  namespace: hsaai
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hsaai-models-pvc
  namespace: hsaai
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 200Gi
